#macro left_tap    mouse_input.tap_left
#macro left_mash   mouse_input.mash_left
#macro left_letgo  mouse_input.letgo_left
#macro right_tap   mouse_input.tap_right
#macro right_mash  mouse_input.mash_right
tap_left = false;
mash_left = false;
letgo_left = false;
tap_right = false;
mash_right = false;